def branch = 'master'
def scmUrl_bericht = 'https://github.com/KarottenMxn/praktikumsbericht.git'

node {
    stage('checkout frontend') {
      git branch: branch, credentialsId: 'sluecke', url: scmUrl_bericht
    }

    stage('npm build') {
      //sh 'npm install react-transition-group'     
      dir ('meinereactsache'){
      sh 'pwd'
      //sh 'npm install'
      //sh 'npm install react-scripts'
      sh 'pwd'
      sh 'npm run build'
      }
    }

    stage('deploy') {
      dir ('meinereactsache'){
        sh 'scp -r -i ~/.ssh/id_rsa build/* fmgame@www472.your-server.de:/public_html'
      }
    }

        stage('notify'){
            mail bcc: '', body: "Build ${env.BUILD_URL} Link to Homepage: http://karottenfabrik.net/praktikum", cc: '', from: 'jenkins@xsltec.de', mimeType: 'text/html', replyTo: '', subject: 'Build and deployed new Bericht', to: 'mail@stefan-luecke.de,magnus@xsltec.de'
        }
}
